fix: update readthedocs yaml to run build only if README.md has changes

diff --git a/.readthedocs.yaml b/.readthedocs.yaml
--- a/.readthedocs.yaml
+++ b/.readthedocs.yaml
@@ -10,6 +10,18 @@ build:
   tools:
     python: "3.13"
   jobs:
+    post_checkout:
+      # Cancel building pull requests when there aren't changed in the docs directory or YAML file.
+      # You can add any other files or directories that you'd like here as well,
+      # like your docs requirements file, or other files that will change your docs build.
+      #
+      # If there are no changes (git diff exits with 0) we force the command to return with 183.
+      # This is a special exit code on Read the Docs that will cancel the build immediately.
+      - |
+        if git diff --quiet origin/main -- README.md;
+        then
+          exit 183;
+        fi
     pre_install:
       - python strip_toc.py # <-- This runs your script before Sphinx builds
 
