refactor: refactor addvideo

diff --git a/addvideo b/addvideo
--- a/addvideo
+++ b/addvideo
@@ -158,14 +158,8 @@ generate_files() {
 
   if "${AUTO_GENERATE_IMAGES:-false}"; then
     # generate image from summary prompt
-    json="$(cat "${summarypromptfname}")" \
-      && prompt="$(imageprompt::get_prompt "$json")" \
-      && caption="$(imageprompt::get_caption "$json")" \
-      && generatedimage="$("${SCRIPT_DIR}/generateimagefromprompt" "$prompt")" \
-      && jpegfname="${month}/jpgs/Day$(printf "%03d" "${doy#0}")Summary.jpg" \
-      && cp "$generatedimage" "$jpegfname" &> /dev/null \
-      && "${SCRIPT_DIR}/addimgtoday" "$jpegfname" "AI-Generated Image: ${caption}" "$doy" \
-      && rm -f "$generatedimage" || exit $EXIT_FILE_GENERATION_FAILED
+    "{SCRIPT_DIR}/addsummaryimagefromprompt" "$summarypromptfname" "$doy" \
+      || die "Failed to generate summary image" $EXIT_FILE_GENERATION_FAILED
   fi
 
   if ! cp "${month}/${COMPACT_FILE}" "${month}/${COMPACT_FILE}.bak"; then
