fix: add check for whether year is leap year

diff --git a/addvideotoday b/addvideotoday
--- a/addvideotoday
+++ b/addvideotoday
@@ -13,6 +13,7 @@ source "${SCRIPT_DIR}/util.sh" || exit 1
 source "${SCRIPT_DIR}/git.sh" || exit 1
 source "${SCRIPT_DIR}/youtube.sh" || exit 1
 source "${SCRIPT_DIR}/vidmd.sh" || exit 1
+source "${SCRIPT_DIR}/date.sh" || exit 1
 source "${SCRIPT_DIR}/lockconfig.sh"
 lock_config_vars "${SCRIPT_DIR}/config.env"
 
@@ -37,6 +38,12 @@ function version() {
 function validate_arguments() {
   if [ $# -ne 2 ]; then
     err "Error: Invalid number of arguments"
+    usage 1
+  fi
+  if [[ "${2}" -eq 366 ]] && [[ "$(daycount "${YEAR}")" -eq "$2" ]]; then
+    return 0
+  else
+    err "Error: "$YEAR" has 365 days only."
     usage 1
   fi
 }
