refactor: refactor addvideotoday and addsummariestodays

diff --git a/addvideotoday b/addvideotoday
--- a/addvideotoday
+++ b/addvideotoday
@@ -195,14 +195,8 @@ function append_video_info() {
 
   if "$AUTO_GENERATE_IMAGES"; then
     # generate image from summary prompt
-    json="$(cat "${summarypromptfname}")" \
-      && prompt="$(imageprompt::get_prompt "$json")" \
-      && caption="$(imageprompt::get_caption "$json")" \
-      && generatedimage="$("${SCRIPT_DIR}/generateimagefromprompt" "$prompt")" \
-      && jpegfname="${month}/jpgs/Day$(printf "%03d" "${doy#0}")${video_id}Summary.jpg" \
-      && cp "$generatedimage" "$jpegfname" &> /dev/null \
-      && "${SCRIPT_DIR}/addimgtoday" "$jpegfname" "AI-Generated Image: ${caption}" "$doy" \
-      && rm -f "$generatedimage" || exit $E_FILE_GENERATION_FAILED
+    "{SCRIPT_DIR}/addsummaryimagefromprompt" "$summarypromptfname" "$doy" \
+      || die "Failed to generate summary image" $E_FILE_GENERATION_FAILED
   fi
 }
 
