fix: add check for whether year is leap year

diff --git a/addvideotoday b/addvideotoday
--- a/addvideotoday
+++ b/addvideotoday
@@ -40,10 +40,12 @@ function validate_arguments() {
     err "Error: Invalid number of arguments"
     usage 1
   fi
-  if [[ "${2}" -eq 366 ]] && [[ "$(daycount "${YEAR}")" -eq "$2" ]]; then
-    return 0
-  else
-    err "Error: ${YEAR} has 365 days only."
+  if ! [[ "${2}" -eq 366 ]] && [[ "$(daycount "${year}")" -eq "$2" ]]; then
+    err "Error: ${year} has 365 days only."
+    usage 1
+  fi
+  if [[ "${2}" -le 0 ]] || [[ "${2}" -gt 366 ]]; then
+    err "Error: Invalid day number ${2}"
     usage 1
   fi
 }
