fix: add correct exit codes to genvidmd and output error message to stderr

diff --git a/genvidmd b/genvidmd
--- a/genvidmd
+++ b/genvidmd
@@ -26,4 +26,7 @@ if ./overlayimg "${1}" "${3}"; then
   else
     usage
   fi
+else
+  echo "The video id '${1}' is invalid." >&2
+  exit 1
 fi
