fix: check to see that python package faster-whisper is installed. fix: check to see that video_id is valid

diff --git a/transcribevideo b/transcribevideo
--- a/transcribevideo
+++ b/transcribevideo
@@ -14,8 +14,12 @@ readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd -
 source "${SCRIPT_DIR}/lib/require.sh"
 source "${SCRIPT_DIR}/lib/curl.sh"
 source "${SCRIPT_DIR}/lib/files.sh"
+source "${SCRIPT_DIR}/lib/python.sh"
+source "${SCRIPT_DIR}/lib/youtube.sh"
 source "${SCRIPT_DIR}/lib/lockconfig.sh"
 lockconfig::lock_config_vars "${SCRIPT_DIR}/config.env"
+
+readonly FASTER_WHISPER="faster-whisper"
 
 # Initialize variables
 VERBOSE=false
@@ -130,7 +134,11 @@ function transcribe_via_webservice() {
 function transcribe_locally() {
   local audio_file="$1"
   if "${USE_FASTER_WHISPER:-false}"; then
-    ./fasterwhisperer.py "$audio_file"
+    if python::is_package_installed "$FASTER_WHISPER"; then
+      ./fasterwhisperer.py "$audio_file"
+    else
+      die "Python package ${FASTER_WHISPER} and its dependencies not available. Exiting..."
+    fi
   else
     whisper --task transcribe --model "${ASR_LOCAL_MODEL:-base}" --output_format txt --language en \
       --initial-prompt "${ASR_INITIAL_PROMPT:-}" --beam-size "${ASR_BEAM_SIZE:-5}" "$audio_file" &> /dev/null || return 1
@@ -145,14 +153,14 @@ function transcribe_audio() {
   ${VERBOSE} && log "Transcribing with Whisper..."
   if ${TRANSCRIBE_LOCALLY:-false}; then
     if check_local_prerequisites; then
-      >&2 echo "Transcribing locally... This may take longer than usual..."
+      log "Transcribing locally... This may take longer than usual..."
       transcribe_locally "$audio_file"
     else
       if "${ENABLE_FAILOVER_MODE:-true}"; then
-        >&2 echo "ffmpeg and/or whisper not available. Trying webservice instead..."
+        log "ffmpeg and/or whisper not available. Trying webservice instead..."
         transcribe_via_webservice "$audio_file"
       else
-        >&2 echo "ffmpeg and/or whisper not available. Exiting..."
+        log "ffmpeg and/or whisper not available. Exiting transcribe_audio function..."
         return
       fi
     fi
@@ -172,10 +180,14 @@ function main() {
   ${DEBUG} && set -x
 
   ${VERBOSE} && log "Downloading audio for video ID: ${VIDEO_ID}"
-  local audio_file="$("${SCRIPT_DIR}/downloadaudio" "${VIDEO_ID}")" \
-    && transcribe_audio "${audio_file}" > "${OUTPUT_FILE}" || return 1
-  if ${VERBOSE}; then
-    log "Transcription saved to: ${OUTPUT_FILE}"
+  if youtube::check_video_exists "${VIDEO_ID}"; then
+    local audio_file="$("${SCRIPT_DIR}/downloadaudio" "${VIDEO_ID}")" \
+      && transcribe_audio "${audio_file}" > "${OUTPUT_FILE}" || return 1
+    if ${VERBOSE}; then
+      log "Transcription saved to: ${OUTPUT_FILE}"
+    fi
+  else
+    die "Video id ${VIDEO_ID} is invalid or private. Exiting..."
   fi
 }
 
